version: "3"

services:
  mysql-test:
    container_name: mysql57
    build:
      context: .
      dockerfile: Dockerfile
    image: 5824600/mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_USER=${MYSQL_USER:-test}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
